runner:
  env:
    - key: WANDB_TOKEN
      value: "VALUE"
    - key: DEBUG
      value: TRUE
  target:
    
  actions:
    prepare:
      command: pipenv
      args: ["install", "--ignore-pipfile"]
    run:
      command: python3
      args: ["./script.py", "--debug", "10"]
    test:
      command: pytest
      args: ["./script-test"]