services:
  discord-runner:
    image: shanduur/:latest
    restart: on-failure
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      DOCKER_HOST: 'unix:///var/run/docker.sock'
      DISCORD_TOKEN: 'TOKEN_HERE'
